package hclschema

import "strings"

// Draft identifies a version of the hcl-schema meta-schema. New drafts may
// tighten validation rules that older drafts accepted, so every schema pins
// the draft it was written against through its `__schema` attribute.
type Draft int

const (
	// DraftUnknown is used when the `__schema` reference does not name a draft
	// this build recognises. It behaves as Draft2025_10 so that unrecognised
	// (for example, vendored or privately hosted) meta-schemas keep the
	// permissive legacy semantics rather than failing closed.
	DraftUnknown Draft = iota

	// Draft2025_10 is the original draft. Blocks declared without a `body`
	// accept arbitrary content, and duplicate declarations are silently
	// resolved first-match-wins.
	Draft2025_10

	// Draft2026_09 adds the type system and tightens structural rules:
	// blocks declared without a `body` are closed, and duplicate or ambiguous
	// declarations are errors.
	Draft2026_09
)

// LatestDraft is the draft used for schemas generated by this package.
const LatestDraft = Draft2026_09

var draftIDs = map[Draft]string{
	DraftUnknown: "unknown",
	Draft2025_10: "2025-10",
	Draft2026_09: "2026-09",
}

// String returns the canonical draft identifier, such as "2026-09".
func (d Draft) String() string {
	if s, ok := draftIDs[d]; ok {
		return s
	}
	return "unknown"
}

// URL returns the canonical published location of the draft's meta-schema.
func (d Draft) URL() string {
	return "https://raw.githubusercontent.com/avestura/hcl-schema/refs/heads/main/schema/draft/" + d.String() + "/.schema.hcl"
}

// Strict reports whether the draft enables the tightened structural rules:
// closed bodies for block declarations that omit `body`, and errors on
// duplicate or ambiguous declarations.
func (d Draft) Strict() bool {
	return d >= Draft2026_09
}

// DraftFromRef derives the draft from a `__schema` reference. Recognising the
// draft is a matter of locating a `draft/<id>/` path segment, so vendored
// copies and mirrors keep working as long as they preserve the path shape.
func DraftFromRef(ref string) Draft {
	norm := strings.ReplaceAll(ref, "\\", "/")
	for d, id := range draftIDs {
		if d == DraftUnknown {
			continue
		}
		if strings.Contains(norm, "draft/"+id+"/") || strings.HasSuffix(norm, "draft/"+id) {
			return d
		}
	}
	return DraftUnknown
}

// effective resolves the draft actually used for validation, honouring a
// caller-supplied override.
func (d Draft) effective(forceStrict bool) Draft {
	if forceStrict && d < Draft2026_09 {
		return Draft2026_09
	}
	if d == DraftUnknown {
		return Draft2025_10
	}
	return d
}
